version: '3.9'

services:
  teamcity:
    image: jetbrains/teamcity-server:2022.04.1
    user: "${UID}:${GID}"
    networks:
      - web
      - default
    volumes:
      - "${TC_DATA}:/data/teamcity_server/datadir"
      - "${TC_LOGS}:/opt/teamcity/logs"
    ports:
      - "8111"
    depends_on:
      - pg_teamcity
    env_file: .env
    labels:
      - "traefik.enable=true"
      - "traefik.backend=teamcity"
      - "traefik.frontend.rule=Host:docker-01.cla.cl-grp.local"
      - "traefik.docker.network=web"
      - "traefik.port=8111"
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"

  pg_teamcity:
    build: ./postgres
    volumes:
      - "${PG_DATA}:/var/lib/postgresql/data"
      - "${PG_BACKUP}:/backups"
    env_file: .env
    labels:
      - "traefik.enable=false"
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"

  traefik:
    image: traefik:1.7-alpine
    restart: on-failure
    command:
      - --logLevel=ERROR
      - --docker
      - --docker.watch=true
      - --docker.exposedByDefault=false
      - --docker.domain=docker.localhost
      - --defaultEntryPoints=http
      - --entryPoints=Name:http Address::80
    ports:
      - "8082:80"
    networks:
      - web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"

networks:
  web:
    external: true